{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-longitudinal
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - numpy
    - pandas
    - scipy
    - statsmodels >=0.9.0
    - patsy
    - scikit-bio
    - seaborn
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - q2-sample-classifier {{ release }}.*
    - q2templates {{ release }}.*
    - q2-sample-classifier {{ release }}.*
    - q2-feature-table {{ release }}.*

test:
  imports:
    - q2_longitudinal
    - qiime2.plugins.longitudinal

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
