{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-longitudinal
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - numpy
    - pandas
    - scipy >=1.5
    - statsmodels >=0.9.0
    - patsy
    - scikit-bio >=0.5.5
    - seaborn
    - qiime2 {{ qiime2 }}
    - q2-types {{ q2_types }}
    - q2-sample-classifier {{ q2_sample_classifier }}
    - q2templates {{ q2templates }}
    - q2-feature-table {{ q2_feature_table }}
    - matplotlib

test:
  requires:
    - pytest

  imports:
    - q2_longitudinal
    - qiime2.plugins.longitudinal

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
